# Generated by Django 3.2.13 on 2023-01-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='travel',
            new_name='travel_id',
        ),
    ]
