# Generated by Django 3.2.13 on 2023-01-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_travel_board_travel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='travel_id',
            new_name='travel',
        ),
    ]
