# Generated by Django 3.2.13 on 2023-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_travel_id_board_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='location',
            field=models.JSONField(),
        ),
    ]
