# Generated by Django 3.2.13 on 2023-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_travel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeImgList',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
