# Generated by Django 3.2.13 on 2023-01-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_place_placeimglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='like_user',
            new_name='likeList',
        ),
        migrations.RemoveField(
            model_name='board',
            name='likeCount',
        ),
        migrations.AlterField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentList', to='community.board'),
        ),
    ]
